### ISSUE TITLE
Config.py

### ISSUE THREAD

**Issue by Djow44** [mxrch/HackTheBot#1]
Great work, i had the same idea but no time ;(
Can you add to your project a sample of config.py

thx

**Comment by mxrch** [comment]
Hey, thank you !

That's not going to be enough for you to use the bot..
You must have that config.py file, and config your Discord server with some categories etc
For the moment it's a little complex, but I almost finished ! And then, I'll add a setup.py with all the instructions 😄 
Don't worry I'll make a post in the forum when it's ready for the public, for the moment you can click on "Watch" on the repo to have updates of the progress !

But if you really want to and you love debugging, here is it :
```
HTB = {
    "email": "",
    "password": "",
    "api_token": ""
}

discord = {
    "bot_token": "",
    "guild_name": ""
}

roles = {
    "noob": "HTB - Noob",
    "script kiddie": "HTB - Script kiddie",
    "hacker": "HTB - Hacker",
    "pro hacker": "HTB - Pro hacker",
    "elite hacker": "HTB - Elite hacker",
    "guru": "HTB - Guru",
    "omniscient": "HTB - Omniscient"
}
```
